config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get 'orders' => 'orders#index_all'
  get 'nextOrder' => 'orders#next_order'

  get 'myorders' => 'orders#myorders'

  get '/users/:user_id/orders/edit' => 'orders#edit'
  

  patch '/users/:user_id/orders' => 'orders#update'

  get    '/signup' => 'users#new'
  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :delivery_schedules
  resources :orders
  resources :users
  resources :products

end

app/models/delivery_schedule.rb
class DeliverySchedule
  include Mongoid::Document
  field :date, type: Date
  field :pickup_location, type: String

  validates_presence_of :date, :pickup_location
end

app/controllers/delivery_schedules_controller.rb
class DeliverySchedulesController < ApplicationController
  before_action :set_schedule, only: [:edit, :update, :destroy]

  def new
    @delivery_schedule = DeliverySchedule.new
  end

  def index
    @delivery_schedules = DeliverySchedule.all
  end

  def create
    @delivery_schedule = DeliverySchedule.new(delivery_schedule_params)
    if @delivery_schedule.save
      redirect_to delivery_schedules_path, notice: 'Delivery schedule added.'
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    if @delivery_schedule.destroy
      redirect_to delivery_schedules_path, notice: 'Delivery schedule deleted.'
    else
      redirect_to delivery_schedules_path, notice: 'Delivery schedule could not be deleted.'
    end
  end

  def update
    if @delivery_schedule.update(delivery_schedule_params)
      redirect_to delivery_schedules_path, notice: 'Delivery date has been updated.'
    else
      render :edit
    end
  end

  private
  def delivery_schedule_params
    params.require(:delivery_schedule).permit(:date, :pickup_location)
  end

  def set_schedule
    @delivery_schedule = DeliverySchedule.find_by(id: params[:id])
  end
end

app/views/delivery_schedules/_form.html.haml
= form_for @delivery_schedule, :html => {class: 'form-horizontal'} do | f |
  .form-group
    = f.label :date, "Delivery Date", { class: "col-sm-3 control-label"}
    .col-sm-8
      = f.text_field :date, class: "form-control"
  .form-group
    = f.label :pickup_location, "Pickup Location", { class: "col-sm-3 control-label"}
    .col-sm-2
      = f.text_field :pickup_location, class: "form-control"
  %br
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Save", { class: "btn btn-md btn-default"}

app/views/delivery_schedules/edit.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title="Edit Delivery date"
  .panel-body
    = render 'form'

app/views/delivery_schedules/index.html.haml
.panel.panel-default
  .panel-heading
    .panel-title.col-md-4 Delivery Dates
    .col-md-offset-10
      = link_to raw("<i class=\"glyphicon glyphicon-plus\"></i> New Date"), new_delivery_schedule_path, :class => "btn btn-sm btn-default"

  .panel-body
    - if !@delivery_schedules.empty?
      %table.table.table-bordered
        %tr
          %th Date
          %th Location
          %th
        - @delivery_schedules.each do |d|
          %tr
            %td
              = d.date
            %td
              = d.pickup_location
            %td
              .btn-group
                = link_to raw("<i class=\"glyphicon glyphicon-edit\"></i> Edit"), edit_delivery_schedule_path(d), :class => "btn btn-sm btn-default"
                = link_to raw("<i class=\"glyphicon glyphicon-trash\"></i> Delete"), delivery_schedule_path(d), :method => :delete, :data => { :confirm => 'Are you sure?' },  :class => "btn btn-sm btn-default"
    - else
      %p
        No Delivery dates found.

app/views/delivery_schedules/new.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title="New Delivery date"
  .panel-body
    = render 'form'