config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get 'orders' => 'orders#index_all'
  get 'nextOrder' => 'orders#next_order'

  get 'myorders' => 'orders#myorders'

  get '/users/:user_id/orders/edit' => 'orders#edit'
  

  patch '/users/:user_id/orders' => 'orders#update'

  get    '/signup' => 'users#new'
  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :delivery_schedules
  resources :orders
  resources :users
  resources :products

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword

  field :user_id, type: Integer
  field :name, type: String
  field :email, type: String
  field :pickup_location, type: String

  field :password_digest, :type => String
  has_secure_password

  attr_accessor :remember_token

  validates_presence_of :user_id, :name, :email, :pickup_location
  validates_uniqueness_of :user_id, :email

  before_save { self.email = email.downcase }

  def is_admin
    user_id == 1
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def to_param
    user_id.to_s
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to users_url, notice: "New User Created"
    else
      flash.now[:error] = "Error creating user #{@user.errors.messages}"
      render new_user_path
    end
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all.order_by(:user_id.asc)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_url, notice: "User #{@user.user_id} was successfully updated."
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User #{@user.user_id} deleted"
  end

  private

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find_by(user_id: params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by(user_id: params[:id])
  end

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def build_edit_path(delivery_date)
    "orders/edit?deliveryDate=#{delivery_date}"
  end

  def user_orders_headers(user)
    user.nil? ? "Orders" : "Orders for #{user.name}"
  end
end

app/views/users/_form.html.haml
= form_for @user, html: {class: "form-horizontal"} do |f|
  .form-group
    = label_tag :user_id, "User ID", { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.text_field :user_id, { class: "form-control"}
  .form-group
    = label_tag :name, "Name", { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.text_field :name, { class: "form-control"}
  .form-group
    = label_tag :name, "Password", { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.password_field :password, { class: "form-control"}
  .form-group
    = label_tag :name, "Password Confirmation", { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.password_field :password_confirmation, { class: "form-control"}
  .form-group
    = label_tag :name, "Email", { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.text_field :email, { class: "form-control"}
  .form-group
    = label_tag :name, "Pickup Location", { class: "col-sm-2 control-label"}
    .col-sm-2
      = f.text_field :pickup_location, { class: "form-control"}
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Save", { class: "btn btn-md btn-default"}

app/views/users/edit.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Edit User
  .panel-body
    = render 'form'

app/views/users/index.html.haml
.panel.panel-default
  .panel-heading
    .panel-title
      .col-xs-8 Current Users
      .col-xs-1.col-xs-offset-2
      = link_to raw("<i class=\"glyphicon glyphicon-plus\"></i> New User"), new_user_path, :class => "btn btn-sm btn-default"
  .panel-body
    - if !@users.empty?
      %table.table.table-bordered
        %tr
          %th.col-sm-2 User Id
          %th.col-sm-5 Name
          %th.col-sm-1 Loc
          %th
        - @users.each do |user|
          %tr
            %td.col-sm-2
              = user.user_id
            %td.col-sm-5
              = user.name
            %td.col-sm-1
              = user.pickup_location
            %td
              .btn-group
                = link_to raw("<i class=\"glyphicon glyphicon-edit\"></i> Edit"), edit_user_path(user), :class => "btn btn-sm btn-default"
                = link_to raw("<i class=\"glyphicon glyphicon-wrench\"></i> Orders"), orders_url(), :class => "btn btn-sm btn-default"
                = link_to raw("<i class=\"glyphicon glyphicon-trash\"></i> Delete"),  user_path(user), :method => :delete, :data => { :confirm => 'Are you sure?' } ,  :class => "btn btn-sm btn-default"
    - else
      %p
        No User found.

app/views/users/new.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Sign up
  .panel-body
    = render 'form'