config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get 'orders' => 'orders#index_all'
  get 'nextOrder' => 'orders#next_order'

  get 'myorders' => 'orders#myorders'

  get '/users/:user_id/orders/edit' => 'orders#edit'
  

  patch '/users/:user_id/orders' => 'orders#update'

  get    '/signup' => 'users#new'
  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :delivery_schedules
  resources :orders
  resources :users
  resources :products

end

app/models/product.rb
class Product
  include Comparable
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :unit, type: String
  field :price, type: Integer
  field :sort_order, type: Integer

  validates_presence_of :name, :unit, :price

  def <=>(other)
    # use Array#<=> to compare the attributes
    [self.sort_order] <=> [other.sort_order]
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url, notice: 'New Product Created'
    else
      render new_product_path
    end
  end

  def new
    @product = Product.new
  end

  def index
    @products = Product.all.order_by(:sort_order.asc)
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_url, notice: "Product #{@product.name} was successfully updated."
    else
      render action: 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: "Product #{@product.name} deleted"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :unit, :price, :sort_order)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product, html: {class: "form-horizontal"} do |f|
  .form-group
    = label_tag :name, "Name",  { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.text_field :name, { class: "form-control"}
  .form-group
    = label_tag :unit, "Unit",  { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.text_field :unit, { class: "form-control"}
  .form-group
    = label_tag :price, "Price",  { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.text_field :price, { class: "form-control"}
  .form-group
    = label_tag :sort_order, "Sort Order",  { class: "col-sm-2 control-label"}
    .col-sm-8
      = f.text_field :sort_order, { class: "form-control"}
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Save", { class: "btn btn-md btn-default"}

app/views/products/edit.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Edit Product
  .panel-body
    = render 'form'

app/views/products/index.html.haml
.panel.panel-default
  .panel-heading.hidden-xs
    .panel-title
      .col-sm-6 Current Products
      .col-sm-3.col-sm-offset-3
        = link_to raw("<i class=\"glyphicon glyphicon-plus\"></i> New Product"), new_product_path, :class => "btn btn-sm btn-default"

  .panel-heading.hidden-sm.hidden-md.hidden-lg
    .panel-title
      .col-xs-6 Current Products
      .col-xs-4.col-xs-offset-1
        = link_to raw("<i class=\"glyphicon glyphicon-plus\"></i> New Product"), new_product_path, :class => "btn btn-sm btn-default"

  .panel-body
    - if !@products.empty?
      %table.table.table-bordered
        %tr
          %th.col-md-6 Product Name
          %th.col-md-1 Unit
          %th.col-md-2 Sort Order
          %th.col-md-3
        - @products.each do |product|
          %tr
            %td.col-md-6
              = product.name
            %td.col-md-1
              = product.unit
            %td.col-md-2
              = product.sort_order
            %td.col-md-3
              .btn-group
                = link_to raw("<i class=\"glyphicon glyphicon-edit\"></i> Edit"), edit_product_path(product), :class => "btn btn-sm btn-default"
                = link_to raw("<i class=\"glyphicon glyphicon-trash\"></i> Delete"),  product_path(product), :method => :delete, :data => { :confirm => 'Are you sure?' },  :class => "btn btn-sm btn-default"
    - else
      %p
        No products found.

app/views/products/new.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Create New Product
  .panel-body
    = render 'form'